import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from 'next/image'
import { signIn, signOut, useSession } from "next-auth/react";
import { HiMagnifyingGlass } from "react-icons/hi2";
import { IoCheckmarkCircle } from "react-icons/io5";

import { api } from "~/utils/api";
import { Formation, Technologie } from "@prisma/client";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const { data: formations } = api.formation.getAll.useQuery()
  const admin = sessionData?.user.admin

  return (
    <>
      <Head>
        <title>Liste des formations</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-white">
        
        <div className="fixed w-full pr-40 border-b-4 border-[#63aeab] bg-white top-0 right-0 left-28 h-[4rem]" />

          <div className="flex item-center justify-between gap-12 fixed w-full pr-40 top-0 right-0 left-28 h-[4rem] text-[#63aeab]">
            <div className="flex item-center justify-evenly">
              <button className="px-10 py-3 font-semibold border-[#0E6073] transition hover:border-b-4 hover:text-[#0E6073]">Vos cours</button>
              <button className="px-10 py-3 font-semibold border-[#0E6073] border-b-4 text-[#0E6073]">Explorer</button>
              <button className="px-10 py-3 font-semibold border-[#0E6073] transition hover:border-b-4 hover:text-[#0E6073]" autoFocus>Gérez les cours</button>
            </div>
            <div className="flex item-center justify-center gap-5">
              <div className="bg-white flex flex-row justify-start items-center width mb-24 w-96 h-12 flex flex-row px-8 rounded-full shadow-[inset_4px_4px_12px_4px_rgba(0,0,0,0.25)]">
                <HiMagnifyingGlass className="h-8 w-8 text-[#989898]"/>
                <input className=" h-10 w-full shadow-none w-full bg-none" type="text"/>
              </div>
              {sessionData && sessionData.user?.image && <Link href={`/components/users/${sessionData.user.id}`}><img src={sessionData.user.image} className="max-w-[3rem]"></img></Link>}
            </div>
          </div>
          <div className="flex flex-col items-center justify-between gap-2 min-h-screen top-0 left-0 bg-[#0E6073] fixed m-w-xs p-2">
              <Link href="/"><img src="/okto.png" className="max-w-[3rem]"></img></Link>
              <AuthShowcase />
          </div>

          <div className="container flex flex-col items-start justify-start gap-12 px-4 py-20 ">
            <div className="flex flex-row items-center justify-between w-full px-10">
              <h1 className="text-3xl font-bold tracking-tight text-[#0E6073]">
                Trouvez le cours parfait
              </h1>
              <div className="flex flex-row items-center justify-evenly">
                <p className="mr-2">Trier par : </p>
                <button className="px-4 py-1 bg-[#0E6073] rounded-full mx-1">
                  <p className="text-[#fff]">Thématique</p>
                </button>
                <button className="px-4 py-1 bg-[#D9D9D9] rounded-full mx-1">
                  <p className="text-[#0E6073]">Progression</p>
                </button>
                <button className="px-4 py-1 bg-[#D9D9D9] rounded-full mx-1">
                  <p className="text-[#0E6073]">Niveau</p>
                </button>
              </div>
            </div>
            {/* <div className="flex flex-col items-center gap-2 fixed">
              <AuthShowcase />
              <Link href="/"><button className="rounded-full bg-[#0E6070]/10 px-10 py-3 font-semibold no-underline transition hover:bg-[#0E6070]/20">Home</button></Link>
            </div> */}

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-5 md:gap-8 w-full">
              {formations as Formation[] && formations && formations.length > 0 && formations.map((forma) => {
                let dif: string;
                switch (forma.difficulte) {
                  case 1: dif = "Débutant"; break;
                  case 2: dif = "Intermédiaire"; break;
                  case 3: dif = "Avancé"; break;
                  default: dif = "Débutant";
                }
                if (!forma.hidden || forma.hidden && admin)
                  return (
                    <Link
                      className="flex flex-col items-center min-w-[50px] max-w-2xl gap-4 rounded-xl bg-[#0E6070]/10 p-4 hover:bg-[#0E6070]/20 relative"
                      href={`/components/formations/${encodeURIComponent(forma.id)}`}
                      key={forma.id}
                    >
                      <Image src="/python.png" width="100" height="100" className="w-5/12 absolute -top-10" alt=""/>
                      <h3 className="text-md font-bold mt-12">{forma.title}</h3>

                      <span className="absolute right-5">
                        {/* {dif} */}
                        {forma.difficulte === 1 && <Easy/>}
                        {forma.difficulte === 2 && <Med/>}
                        {forma.difficulte === 3 && <Hard/>}
                      </span>
                      <IoCheckmarkCircle className="h-7 w-7 text-[#0E6073] absolute left-5"/>
                    </Link>
                  )
              })}
          </div>


        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div>
      {sessionData?.user.admin && <Link href="/components/admin"><img src="https://icones.pro/wp-content/uploads/2022/02/services-parametres-et-icone-d-engrenage-gris.png" className="max-w-[3rem]"></img></Link>}
      <button
        className="rounded-full px-3 py-3 font-semibold  no-underline transition hover:bg-white/10"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? <img src="/arrow.png" className="max-w-[1.5rem]"></img> : "Sign in"}
      </button>
    </div>

  );
};

const Easy: React.FC = () => {
  return (
      <div className="flex flex-row items-end">
          <svg width="6" height="11">
              <rect width="6" height="11" className="fill-[#0E6073]" />
          </svg>
          <svg width="6" height="19" className="mx-1">
              < rect width="6" height="19" className="fill-[#989898] dark:fill-[#2EA3A5]" />
          </svg >
          <svg width="6" height="28">
              <rect width="6" height="28" className="fill-[#989898] dark:fill-[#2EA3A5]" />
          </svg >
      </div >
  );
};

const Med: React.FC = () => {
  return (
      <div className="flex flex-row items-end">
          <svg width="6" height="11">
              <rect width="6" height="11" className="fill-[#0E6073]" />
          </svg>
          <svg width="6" height="19" className="mx-1">
              < rect width="6" height="19" className="fill-[#0E6073]" />
          </svg >
          <svg width="6" height="28">
              <rect width="6" height="28" className="fill-[#989898] dark:fill-[#2EA3A5]" />
          </svg >
      </div >
  );
};

const Hard: React.FC = () => {
  return (
      <div className="flex flex-row items-end">
          <svg width="6" height="11">
              <rect width="6" height="11" className="fill-[#0E6073]" />
          </svg>
          <svg width="6" height="19" className="mx-1">
              < rect width="6" height="19" className="fill-[#0E6073]" />
          </svg >
          <svg width="6" height="28">
              <rect width="6" height="28" className="fill-[#0E6073]" />
          </svg >
      </div >
  );
};

