import { type NextPage } from 'next';
import { GetServerSideProps } from 'next'
import { InferGetServerSidePropsType } from 'next'
import { getServerSession } from "next-auth";
import Head from "next/head";
import Link from "next/link";
import { getSession, signIn, signOut, useSession } from "next-auth/react";
import { FaArrowLeft, FaVideo, FaGithub } from "react-icons/fa";

import { api } from "~/utils/api";
import { prisma } from '~/server/db';
import { Etape, EtapeType, Lecon, Formation } from '@prisma/client';
import Header from '~/pages/components/header';
import Openable from '~/pages/components/openable';
import Title from '~/pages/components/title';

export const getServerSideProps: GetServerSideProps<{
    lecon: Lecon;
    formation: Formation
}> = async function (context) {

    const session = await getSession(context)
    const admin = session?.user.admin

    const lecon = await prisma.lecon.findUnique({
        where: {
            id: context.query.id as string
        },
    });
    const idf = lecon?.idf;

    const formation = await prisma.formation.findUnique({
        where: {
            id: lecon?.idf as string
        },
        include: {
            techs: true,
            lecons: true
        }
    });

    if (!session || !admin) {
      return {
        redirect: {
          destination: '/',
          permanent: false,
        },
      }
    }
    else {
        
        return {
            props: {
                lecon: JSON.parse(JSON.stringify(lecon)) as Lecon,
                formation: JSON.parse(JSON.stringify(formation)) as Formation
            }
        };
    }
    
};

const etapes: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ lecon, formation }) => {
    const { data: sessionData } = useSession();
    const admin = sessionData?.user.admin

    const { data: typeList } = api.type.getAll.useQuery()

    const idL = lecon.id
    const idf = lecon.idf
    const addEtape = api.etape.create.useMutation()
    const { data: etapes } = api.etape.getAll.useQuery({ id: idL })

    return (
        <>
            <Head>
                <title>{lecon.title}</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/okto.png" />
            </Head>

            <main className="flex min-h-screen bg-white flex flex-col justify-between pb-20">

                <div className="flex flex-col items-start justify-start pl-28 pt-20 pr-6 w-12/12">
                    <Title title={lecon.title + " de " + formation.title} link={`/formations/${encodeURIComponent(lecon.idf)}`} />
                    <div className="flex flex-col items-center pr-10 w-7/12 mt-6">
                            <div className="flex flex-row items-center justify-between w-full">
                                <h3 className="text-xl font-bold tracking-tight text-[#0E6073]">Description</h3>
                                <div className="flex flex-row ">
                                    <div className="flex flex-row items-center ml-4">
                                        <FaVideo className="h-7 w-7 text-[#989898]" />
                                        <p className="ml-2 text-sm font-Inter text-[#989898]">Cours vidéo</p>
                                    </div>
                                </div>
                            </div>
                            <div className="text-sm font-Inter text-[#222222] self-start mt-3" dangerouslySetInnerHTML={{ __html: lecon.description }} />
                            <div className="self-end flex flex-row items-center justify-center w-8/12">
                                <button className="text-white w-8/12 bg-[#0E6073] h-14 rounded-full my-3 self-end ml-2 hover:bg-[#0a4654]">
                                    Voir la vidéo du cours
                                </button>
                                <button className="text-white w-3/12 bg-[#2EA3A5] flex flex-row items-center justify-center h-14 rounded-full my-3 ml-2 self-end hover:bg-[#248082]">
                                    <FaGithub className="h-7 w-7 text-white" />
                                </button>
                            </div>
                            <div className="flex flex-col items-start w-full mt-5">
                                <h3 className="text-xl font-bold tracking-tight text-[#0E6073]">Transcript</h3>
                                <p className="text-sm font-Inter text-[#222222] self-start mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus interdum hendrerit metus, non pretium libero. Nullam pulvinar, velit vel varius congue, eros libero varius est, nec semper tortor ligula quis sem. Nam blandit id turpis sed feugiat. Maecenas tincidunt aliquet tempor. Nam hendrerit ex laoreet sapien bibendum gravida. Donec ornare lorem vitae arcu fermentum, ac consectetur est accumsan. Sed elementum urna id odio auctor, nec tincidunt nibh sagittis. Aenean sodales leo eu metus bibendum laoreet at vel ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sollicitudin augue massa, vel pretium metus sollicitudin eu.</p>
                                <p className="text-sm font-Inter text-[#222222] self-start mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus interdum hendrerit metus, non pretium libero. Nullam pulvinar, velit vel varius congue, eros libero varius est, nec semper tortor ligula quis sem. Nam blandit id turpis sed feugiat. Maecenas tincidunt aliquet tempor. Nam hendrerit ex laoreet sapien bibendum gravida. Donec ornare lorem vitae arcu fermentum, ac consectetur est accumsan. Sed elementum urna id odio auctor, nec tincidunt nibh sagittis. Aenean sodales leo eu metus bibendum laoreet at vel ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sollicitudin augue massa, vel pretium metus sollicitudin eu.</p>
                                <p className="text-sm font-Inter text-[#222222] self-start mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus interdum hendrerit metus, non pretium libero. Nullam pulvinar, velit vel varius congue, eros libero varius est, nec semper tortor ligula quis sem. Nam blandit id turpis sed feugiat. Maecenas tincidunt aliquet tempor. Nam hendrerit ex laoreet sapien bibendum gravida. Donec ornare lorem vitae arcu fermentum, ac consectetur est accumsan. Sed elementum urna id odio auctor, nec tincidunt nibh sagittis. Aenean sodales leo eu metus bibendum laoreet at vel ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sollicitudin augue massa, vel pretium metus sollicitudin eu.</p>
                                <p className="text-sm font-Inter text-[#222222] self-start mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus interdum hendrerit metus, non pretium libero. Nullam pulvinar, velit vel varius congue, eros libero varius est, nec semper tortor ligula quis sem. Nam blandit id turpis sed feugiat. Maecenas tincidunt aliquet tempor. Nam hendrerit ex laoreet sapien bibendum gravida. Donec ornare lorem vitae arcu fermentum, ac consectetur est accumsan. Sed elementum urna id odio auctor, nec tincidunt nibh sagittis. Aenean sodales leo eu metus bibendum laoreet at vel ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sollicitudin augue massa, vel pretium metus sollicitudin eu.</p>
                            </div>
                    </div>
                </div>
                <div className="w-5/12 fixed right-0 flex flex-col items-center justify-between h-5/6 pt-10 mr-5">
                    <div className="w-4/6 mt-16">
                        <Openable data={lecon} setSelected={undefined} selected={lecon.id} nav={''} />
                    </div>
                    <button className="text-white w-4/6 bg-[#0E6073] h-14 rounded-full hover:bg-[#0a4654]">
                        Modifier la leçon
                    </button>

                </div>
            </main>
            <Header selected={3}/>
        </>
    );
};

export default etapes;