import { type NextPage } from "next";
import React, { useState } from 'react';
import Head from "next/head";
import Header from "../components/header";
import Link from "next/link";
import Image from 'next/image'
import { signIn, signOut, useSession } from "next-auth/react";
import { IoCheckmarkCircle } from "react-icons/io5";

import { api } from "~/utils/api";
import { Difficulty } from "~/pages/components/difficulties";
import { Formation, Technologie } from "@prisma/client";
import Lesson from "../components/lesson";
import Title from "../components/title";
import Techno from "../components/techno";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const { data: formations } = api.formation.getAll.useQuery()
  const { data: technologies } = api.technologie.getAll.useQuery()
  const admin = sessionData?.user.admin
  const [filterType, setFilterType] = useState("alphabetique")

  function changeFilterType(type: string) {
    setFilterType(type)
  }

  technologies as Technologie[] && technologies && technologies.length > 0 && filterType == "alphabetique" ? technologies.sort(function (a, b) {
    if (a.name < b.name) {
      return -1;
    }
    if (a.name > b.name) {
      return 1;
    }
    return 0;
  }) : formations as Formation[] && formations && formations.length > 0 && filterType == "diff" && formations.sort(function (a, b) {
    return a.difficulte - b.difficulte;
  })

  return (
    <>
      <Head>
        <title>Liste des formations</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/okto.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-start bg-white dark:bg-[#041F25]">

        <div className="flex flex-col items-start justify-start gap-12 pl-28 pt-20 pr-6 w-full">
          <div className="flex flex-row items-center justify-between w-full">
            <Title title={"Trouvez le cours parfait"} link={""} />
            <div className="flex flex-row items-center justify-evenly">
              <p className="mr-2">Trier par : </p>
              
              {filterType === "alphabetique" ? <button className="px-4 py-1 bg-[#0E6073] rounded-full mx-1" onClick={() => changeFilterType("alphabetique")}>
                <p className="text-[#fff]">Thématique</p>
              </button> :
              <button className="px-4 py-1 bg-[#D9D9D9] rounded-full mx-1" onClick={() => changeFilterType("alphabetique")}>
                <p className="text-[#0E6073]">Thématique</p>
              </button>
              }
              {filterType === "progress" ? <button className="px-4 py-1 bg-[#0E6073] rounded-full mx-1" onClick={() => changeFilterType("progress")}>
                <p className="text-[#fff]">Progression</p>
              </button> :
              <button className="px-4 py-1 bg-[#D9D9D9] rounded-full mx-1" onClick={() => changeFilterType("progress")}>
                <p className="text-[#0E6073]">Progression</p>
              </button>
              }
              {filterType === "diff" ? <button className="px-4 py-1 bg-[#0E6073] rounded-full mx-1" onClick={() => changeFilterType("diff")}>
                <p className="text-[#fff]">Niveau</p>
              </button> :
              <button className="px-4 py-1 bg-[#D9D9D9] rounded-full mx-1" onClick={() => changeFilterType("diff")}>
              <p className="text-[#0E6073]">Niveau</p>
            </button>}
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-5 md:gap-8 w-full">
            {filterType === "alphabetique" ? 
              technologies as Technologie[] && technologies && technologies.length > 0 && technologies.map((techno) => {
                return (
                  <Techno data={techno} key={techno.id} />
                )
              }) : formations as Formation[] && formations && formations.length > 0 && formations.map((forma) => {
                if (!forma.hidden || forma.hidden && admin)
                  return (
                    <Lesson data={forma} />
                  )
              })
            }
          </div>
        </div>
        <Header selected={2}/>
      </main>
    </>
  );
};

export default Home;