import { type NextPage } from 'next';
import Head from "next/head";
import Image from 'next/image'
import { Difficulty, DifficultyText } from "~/pages/components/difficulties"
import { FaPenAlt } from "react-icons/fa";

import Header from './components/header';
import { useState } from 'react';
import Openable from './components/openable';

const Dashboard: NextPage = () => {

    const [selected, setSelected] = useState(1)

  const DATA = [{
        id: 1,
        title: "Initiation JS",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nulla nisl, placerat sid sed mauris vitae, alea sit vestibulum sollicitudin set libero onec nulla nisl, placerat.",
        lessons: [
            {
                id: 1,
                title: "Leçon 1",
                status: "finished"
            },
            {
                id: 2,
                title: "Exercice 1",
                status: "finished"
            },
            {
                id: 3,
                title: "Exercice 2",
                status: "notStarted"
            }
        ],
        diff: 1
    },{
        id: 2,
        title: "JS intermédiaire",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nulla nisl, placerat sid sed mauris vitae, alea sit vestibulum sollicitudin set libero onec nulla nisl, placerat.",
        lessons: [
            {
                id: 1,
                title: "Leçon 1",
                status: "finished"
            },
            {
                id: 2,
                title: "Exercice 1",
                status: "finished"
            },
            {
                id: 3,
                title: "Exercice 2",
                status: "notStarted"
            }
        ],
        diff: 2
    },
    ]

    return (
        <>
            <Head>
                <title>My dashboard</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/okto.png" />
            </Head>

            <main className="flex min-h-screen bg-white flex flex-row justify-between pb-20">
                <div className="flex flex-col items-start justify-start gap-12 pl-24 pt-20 pr-6 w-9/12">
                    <h1 className="text-3xl font-bold tracking-tight text-[#0E6073] mx-10">Reprendre où vous en étiez</h1>

                    {DATA.map((item) =>
                        selected === item.id ?
                        <Openable data={item} selected={() => setSelected(props.data.id)}/> 
                        :
                        <div className="flex flex-row items-center w-full gap-3 rounded-xl bg-white py-7 pr-10 mt-6 shadow-[0px_10px_30px_0px_rgba(0,0,0,0.25)] relative" onClick={() => setSelected(item.id)} key={item.id}>
                            <div className="flex flex-col justify-end max-w-20 max-h-20 -top-4 -left-5 absolute">
                                <Image src="/python.png" width="100" height="100" alt=""/>
                            </div>
                            <div className="ml-20 flex flex-col justify-start items-start">
                                <h3 className="font-bold text-[#0E6073] mb-3 text-lg">{item.title}</h3>
                                <p className="text-sm font-Inter text-[#989898] text-left">{item.description}</p>
                            </div>
                            <div className="flex flex-col justify-start h-full">
                                <DifficultyText level={item.diff}/>
                                <div className="flex flex-row justify-start items-center mt-5">
                                    <FaPenAlt className="h-7 w-7 text-[#989898] dark:text-[#2EA3A5]"/>
                                    <p className="text-sm ml-3 font-Inter text-[#989898] dark:text-[#2EA3A5]">3 leçons</p>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                <div className="w-3/12 bg-[#0E6073] fixed right-0 flex flex-col items-start justify-start h-full pt-24 px-10">
                    <h3 className="font-bold text-white mb-8 w-full">Cours terminés</h3>
                    <div className="bg-white w-full h-14 rounded-xl flex flex-row justify-between items-center pr-5 mb-3">
                        <div className="flex flex-row justify-start items-center relative">
                            <Image src="/python.png" width="60" height="60" className="top-0" alt=""/>
                            <h3 className="font-bold text-[#0E6073]">Initiation JS</h3>
                        </div>
                        <Difficulty level={1}/>
                    </div>
                    <div className="bg-white w-full h-14 rounded-xl flex flex-row justify-between items-center pr-5 mb-3">
                        <div className="flex flex-row justify-start items-center relative">
                            <Image src="/python.png" width="60" height="60" className="top-0" alt=""/>
                            <h3 className="font-bold text-[#0E6073]">Initiation JS</h3>
                        </div>
                        <Difficulty level={1}/>
                    </div>
                </div>
                <Header selected={1}/>
            </main>
        </>
    );
};

export default Dashboard;