import { GetServerSideProps, InferGetServerSidePropsType, type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from 'next/image'
import { signIn, signOut, useSession } from "next-auth/react";

import { FaPenAlt, FaMoon, FaSun } from "react-icons/fa";
import { HiMagnifyingGlass } from "react-icons/hi2";

import { api } from "~/utils/api";
import { EasyText, MedText, HardText } from "~/utils/function"

import { Formation, Technologie } from "@prisma/client";
import dynamic from "next/dynamic";
import { useTheme } from "next-themes";
import { prisma } from "~/server/db";

const Home: NextPage = () => {
  const { systemTheme, theme, setTheme } = useTheme();
  const currentTheme = theme === 'system' ? systemTheme : theme;

  const { data: sessionData } = useSession();
  const admin = sessionData?.user.admin

  const {data: formations }= api.formation.getAll.useQuery();
  const getLecon = api.formation.getLecons.useMutation();
  const { data: last4 } = api.formation.getLast4.useQuery()

  const { data: techList } = api.technologie.getAll.useQuery()

  return (
    <>
      <Head>
        <title>OktoStudent</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/okto.png" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
        </style>
      </Head>
      <Image src={theme == "dark" ? "/homescreen-darkmode-wave.svg" : "/homescreen-wave.svg"} width="0" height="1500" className="w-screen z-0 absolute" alt="" />
      <main className="flex min-h-screen flex-col items-center justify-center bg-white z-10 dark:bg-[#041F25]">
        <div className="flex flex-row items-start justify-between w-full px-16 z-10 mt-10">
          <Image src="/okto.png" alt="Logo Oktopod" width="64" height="64" />
          <div className="flex flex-row justify-around items-center">
            {sessionData?.user.admin && <Link href="/components/admin"><img src="https://icones.pro/wp-content/uploads/2022/02/services-parametres-et-icone-d-engrenage-gris.png" className="max-w-[3rem]"></img></Link>}
            <button
              className="rounded-full px-3 py-3 font-semibold  no-underline transition hover:bg-white/10"
              onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
              <p className="text-white font-Inter">CONNEXION</p>
            </button>
            <button onClick={() => theme === "dark" ? setTheme('light') : setTheme("dark")} className="flex flex-row justify-center items-center ml-8 rounded-full bg-white/10 w-10 h-10 shadow-md">
              {theme == "dark" ? <FaSun className="w-2/5 text-[#fff]" /> : <FaMoon className="w-2/5 text-[#fff]" />}
            </button>
          </div>
        </div>
        <div className="container flex flex-col items-center columns-12 justify-center z-10 pt-10 px-12 ">
          <div className="container flex flex-row items-center justify-center mb-12">
            <div className="w-3/5">
              <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] mb-12">
                Des cours sur mesure
              </h1>
              <p className="text-white text-xl font-Inter">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nulla nisl, placerat sed mauris vitae, vestibulum sollicitudin libero.</p>
            </div>
            <Image src="/learn.png" width="1037" height="991" className="w-4/5" alt="" />
          </div>
          {/* <AuthShowcase />
          <Link href="/components/formation"><button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">Liste Formations</button></Link> */}

          {/*<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {techList as Technologie[] && techList && techList.length > 0 && techList.map((tech) => {
              return (
                <Link
                  className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                  href={`/components/technologies/${encodeURIComponent(tech.id)}`}
                  key={tech.id}
                >


                  <h3 className="text-2xl font-bold">{tech.name}</h3>
                </Link>
              )
            })}
          </div>*/}

          <h1 className="text-4xl self-start mb-24 mt-20 text-[#0E6073] dark:text-white">Nouveautés</h1>

          <div className="flex flex-row w-full h-96 items-center mt-6">
            {last4 as Formation[] && last4 && last4.length > 0 && last4.map((forma) => {
              if (!forma.hidden || (forma.hidden && admin)) {
                return (
                  <div className="flex flex-col items-center bg-white/20 rounded-3xl shadow-lg w-full h-96 mx-2 relative" key={forma.id}>
                    <div className="absolute -top-20 flex items-end justify-end w-[170px] h-[150px]">
                      {forma.techs[0] && forma.techs[0].logo && <img src={forma.techs[0].logo} alt="" />}
                    </div>
                    <div className="w-full px-4 flex flex-col items-center mt-20">
                      <h3 className="text-3xl mb-3 text-cyan-700 text-[#0E6073] dark:text-[#63AEAB]">{forma.title}</h3>
                      <div className="text-sm font-Inter dark:text-[#2EA3A5]" dangerouslySetInnerHTML={{ __html: forma.description }} />
                    </div>
                    <div className="flex flex-row items-center justify-around mt-5 w-full px-5 absolute bottom-8">
                      <div className="flex flex-row items-center justify-center">
                        {forma.difficulte === 1 && <EasyText />}
                        {forma.difficulte === 2 && <MedText />}
                        {forma.difficulte === 3 && <HardText />}
                      </div>
                      <div className="flex flex-row items-center justify-center">
                        <FaPenAlt className="h-7 w-7 text-[#989898] dark:text-[#2EA3A5]" />
                        <p className="ml-2 text-sm font-Inter text-[#989898] dark:text-[#2EA3A5]">{forma.lecons.length.toString()} leçons</p>
                      </div>
                    </div>
                  </div>
                )
              }
            })}
          </div>

          <h1 className="text-4xl self-start mb-11 mt-12 text-[#0E6073] dark:text-white">Trouvez le bon cours pour vous</h1>
          <div className="bg-white width mb-24 w-8/12 h-16 flex flex-row items-center px-8 rounded-full shadow-[inset_4px_4px_12px_4px_rgba(0,0,0,0.25)]">
            <HiMagnifyingGlass className="h-9 w-9 text-[#989898]" />
            <input className=" h-16 w-40 shadow-none w-full bg-transparent" type="text" />
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-4 w-full items-center gap-y-32 mt-6">
            {formations as Formation[] && formations && formations.length > 0 && formations.map((forma) => {
              if (!forma.hidden || (forma.hidden && admin)) {
                return (
                  <div className="flex flex-col items-center bg-white/20 rounded-3xl shadow-lg w-full h-96 mx-2 relative" key={forma.id}>
                    <div className="absolute -top-20 flex items-end justify-end w-[170px] h-[150px]">
                      {forma.techs[0] && forma.techs[0].logo && <img src={forma.techs[0].logo} alt="" />}
                    </div>
                    <div className="w-full px-4 flex flex-col items-center mt-20">
                      <h3 className="text-3xl mb-3 text-cyan-700 text-[#0E6073] dark:text-[#63AEAB]">{forma.title}</h3>
                      <div className="text-sm font-Inter dark:text-[#2EA3A5]" dangerouslySetInnerHTML={{ __html: forma.description }} />
                    </div>
                    <div className="flex flex-row items-center justify-around mt-5 w-full px-5 absolute bottom-8">
                      <div className="flex flex-row items-center justify-center">
                        {forma.difficulte === 1 && <EasyText />}
                        {forma.difficulte === 2 && <MedText />}
                        {forma.difficulte === 3 && <HardText />}
                      </div>
                      <div className="flex flex-row items-center justify-center">
                        <FaPenAlt className="h-7 w-7 text-[#989898] dark:text-[#2EA3A5]" />
                        <p className="ml-2 text-sm font-Inter text-[#989898] dark:text-[#2EA3A5]">{forma.lecons.length.toString()} leçons</p>
                      </div>
                    </div>
                  </div>
                )
              }
            })}
          </div>

          {/* <img src="https://media.discordapp.net/attachments/688793736620146689/915869475423813662/20210709_215217.gif" className="max-w-[12em]"></img> */}

        </div>
        <div className="w-full bg-[#0e6370] h-40 bottom-0 mt-12 flex flex-row px-48 justify-between items-center">
          <div className="flex flex-row justify-between items-center">
            <Image src="/Oktopod-carré-blanc.png" width="100" height="30" className="h-20 mr-4" alt="Logo Oktopod" />
            <p className="text-sm font-Inter text-white mx-4">© 2023 Oktopod</p>
          </div>
          <div className="flex flex-row justify-between items-center">
            <p className="text-sm font-Inter text-white mx-4 hover:text-[#63AEAB]">Mentions légales</p>
            <button onClick={sessionData ? () => void signOut() : () => void signIn()} className="text-sm font-Inter text-white pl-4 border-l-2 hover:text-[#63AEAB]">{sessionData ? "Déconnexion" : "Connexion"}</button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div>
      {sessionData && sessionData.user?.image && <Link href={`/components/users/${sessionData.user.id}`}><img src={sessionData.user.image} className="max-w-[3rem]"></img></Link>}
      {sessionData?.user.admin && <Link href="/components/admin"><img src="https://icones.pro/wp-content/uploads/2022/02/services-parametres-et-icone-d-engrenage-gris.png" className="max-w-[3rem]"></img></Link>}
      {sessionData?.user.admin && <Link href="/components/admin/main"><img src="https://icones.pro/wp-content/uploads/2022/02/services-parametres-et-icone-d-engrenage-gris.png" className="max-w-[3rem]"></img></Link>}
      <button
        className="rounded-full px-3 py-3 font-semibold  no-underline transition hover:bg-white/10"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? <img src="/arrow.png" className="max-w-[1.5rem]"></img> : "Sign in"}
      </button>
    </div>

  );
};

