import { type NextPage } from 'next';
import Head from "next/head";

import Header from './components/header';

const Technologies: NextPage = () => {

    return (
        <>
            <Head>
                <title>My dashboard</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/okto.png" />
            </Head>

            <main className="flex min-h-screen bg-white justify-between">
                <div >
                    <p className="mx-20 my-20 text-black">test</p>
                </div>
                <Header selected={1}/>
            </main>
        </>
    );
};

export default Technologies;