import { type NextPage } from 'next';
import { GetServerSideProps } from 'next'
import { InferGetServerSidePropsType } from 'next'
import { getServerSession } from "next-auth";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { prisma } from '~/server/db';
import { Etape, EtapeType, Lecon } from '@prisma/client';

export const getServerSideProps: GetServerSideProps<{
    etape: Etape;
}> = async function (context) {
    const etape = await prisma.etape.findUnique({
        where: {
            id: context.query.id as string
        },
    });
    return {
        props: {
            etape: JSON.parse(JSON.stringify(etape)) as Etape
        }
    };
};

const etapes: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ etape }) => {
    const { data: sessionData } = useSession();
    const admin = sessionData?.user.admin

    const { data: typeList } = api.type.getAll.useQuery()

    const idL = etape.id
    const addEtape = api.etape.create.useMutation()
    const { data: etapes } = api.etape.getAll.useQuery({ id: idL })

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                {etape &&
                    <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                            <span className="text-[hsl(280,100%,70%)]">{etape.name}</span> etape
                        </h1>

                        <h3 className="text-2xl font-bold">{etape.name}</h3>
                        <div className="text-lg">
                            {etape.description}
                        </div>

                        <div className="text-lg">
                            {etape.code}
                        </div>
                        

                        <iframe src="https://stackblitz.com/github/milocartal/launch-edu?file=launch-edu-okto/src/pages/index.tsx.ts&embed=1&view=editor&hideExplorer=1" />

                        <div className="flex items-center gap-2">
                            <AuthShowcase />
                            <Link href="/"><button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">Home</button></Link>
                            <Link href="/components/formation"><button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">Liste etapes</button></Link>
                        </div>

                    </div>
                }
            </main>
        </>
    );
};

export default etapes;

const AuthShowcase: React.FC = () => {
    const { data: sessionData } = useSession();

    return (
        <div className="flex flex-col items-center justify-center gap-4">
            <p className="text-center text-2xl text-white">
                {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
            </p>
            {sessionData?.user.admin && <Link href="/components/admin"><button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">Admin</button></Link>}
            <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
                {sessionData ? "Sign out" : "Sign in"}
            </button>
        </div>
    );
};