import { GetServerSideProps, type NextPage } from "next";
import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import { type Session as SessionAuth } from 'next-auth'

import { api } from "../../utils/api";
import { Technologie } from '@prisma/client';

import dynamic from "next/dynamic";
import { useState } from "react";

import { HiXMark } from "react-icons/hi2"
import { HiMagnifyingGlass } from "react-icons/hi2";


import Header from "../components/header"
import Title from "../components/title";

const QuillNoSSRWrapper = dynamic(import('react-quill'), {
    ssr: false,
    loading: () => <p>Loading ...</p>,
})

export const getServerSideProps: GetServerSideProps<{
    session: SessionAuth;
}> = async function (context) {
    const session = await getSession(context)
    const admin = session?.user.admin

    if (!session || !admin) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        }
    }

    return {
        props: { session }
    }
};

const Admin: NextPage = () => {

    const [content, setContent] = useState('');
    const [hidden, setHide] = useState(true);
    const [tab, setTab] = useState("normal")
    const [selectedTech, setSelectTech] = useState<string>()
    const [urlLogo, setLogo] = useState("")
    const [SearchTag, setSearchTag] = useState('');

    const { data: sessionData } = useSession();

    const user = sessionData?.user.admin

    const addtech = api.technologie.create.useMutation()
    const deltech = api.technologie.delete.useMutation()
    const { data: techList } = api.technologie.getAll.useQuery()

    const addFormation = api.formation.create.useMutation()

    async function handlerAddTech(event: React.SyntheticEvent) {
        //event.preventDefault()
        const target = event.target as typeof event.target & {
            techName: { value: string };
            logoTech: { value: string };
        };
        const nameT = target.techName.value;
        const logoUrl = target.logoTech.value;
        await addtech.mutateAsync({ name: nameT, url: logoUrl })
    }

    async function handleFormation(event: React.SyntheticEvent) {
        //event.preventDefault()
        const target = event.target as typeof event.target & {
            formTitle: { value: string };
            description: { value: string };
            difficulte: { value: string };
            techno: { value: string }
        };
        const title = target.formTitle.value;
        //const desc = target.description.value;
        const diff: number = +target.difficulte.value;
        const techno = target.techno.value;

        await addFormation.mutateAsync({ title: title, description: content, difficulte: diff, techno: techno, hide: hidden })
    }

    const handleSearchTag = (e: React.ChangeEvent<HTMLInputElement>) => {
        let value = e.target.value;
        setSearchTag(value);
    };

    return (
        <>
            <Head>
                <title>Créer une Formation</title>
                <meta name="description" content="Generated by create-t3-app" />

            </Head>
            {user ? <main className="flex h-screen bg-white dark:bg-[#082F38] flex flex-col justify-between pb-20 dark:bg-[#082F38]">
                <div className="flex flex-col items-start justify-start pl-28 pt-20 pr-6 w-full">
                    <Title title={"Créer une formation"} link={"/admin"} />


                    <form onSubmit={handleFormation} className="flex justify-center gap-[15%] item-center w-full h-full text-[#041f25] dark:text-white" method="POST">
                        <fieldset className="flex flex-col max-h-[60%] w-[40%]">
                            
                            <p className="mb-3 mt-3">Choisir une thématique:</p>
                            <div className="p-2 flex flex-row justify-center rounded-t-lg bg-[#0E6073] dark:bg-[#05262E] w-full">
                                <div className="bg-white dark:bg-[#041F25] flex flex-row justify-start items-center width w-96 h-12 px-8 rounded-full shadow-[inset_4px_5px_12px_4px_rgba(0,0,0,0.25)]">
                                    <HiMagnifyingGlass className="h-8 w-8 text-[#989898] dark:text-[#63AEAB]" />
                                    <input type='text' name="lecon tag" placeholder='Rechercher un tag' className="h-10 shadow-none w-full bg-transparent text-black dark:text-white ml-1" autoComplete="off" onChange={handleSearchTag}/>
                                </div>
                            </div>
                            {/* <input type='text' name="lecon tag" placeholder='Rechercher un tag' className="p-[1rem] rounded-t-lg bg-none dark:bg-[#041F25] shadow-[inset_4px_5px_12px_6px_rgba(0,0,0,0.25)] w-full" autoComplete="off" onChange={handleSearchTag} /> */}
                            <fieldset className="flex flex-col justify-between w-full shadow-xl shadow-black/30 rounded-b-lg">
                                <fieldset className="flex flex-col h-80 w-full rounded-t-lg" id="listTech">
                                    {techList as Technologie[] && techList && techList.length > 0 && techList.filter((techno) => { return techno.name.toLowerCase().includes(SearchTag.toLowerCase()) }).map((techno) => {
                                        return (
                                            <label className={`container flex items-center justify-between p-5 ${selectedTech === techno.id ? 'bg-[#0e6073] text-white' : 'hover:bg-[#0e6073]/10'}`} key={techno.id}>
                                                <p className="">{techno.name}</p>
                                                <input type="radio" name="techno" value={techno.id} onChange={(e) => setSelectTech(e.target.value)} required className="mt-[7px]" />
                                            </label>
                                        )
                                    })}
                                </fieldset>
                                <div className="flex items-center justify-center h-[5rem] w-full bg-[#2ea3a5] text-white hover:cursor-pointer transition hover:bg-[#0e6073] rounded-b-lg" onClick={(e) => setTab("tech")}>
                                    + Ajouter une nouvelle technologie
                                </div>
                            </fieldset>
                        </fieldset>

                        <fieldset className="flex flex-col gap-6 justify-center item-center w-[60%] h-full">
                            <input name="formTitle" id="formTitle" type="text" placeholder="Titre de la formation" required className="p-[1rem] rounded-lg bg-none dark:bg-[#041F25] shadow-[inset_4px_5px_12px_6px_rgba(0,0,0,0.25)] w-full" autoComplete="off" />

                            <QuillNoSSRWrapper theme="snow" onChange={setContent} placeholder="Description" className="h-[40%] shadow-xl pb-11 dark:bg-[#041F25] dark:text-white" />
                            <fieldset className="mt-3 flex gap-5 w-full justify-center">
                                <legend>Difficulté:</legend>
                                <div className="flex flex-col items-center gap-2">
                                    <label htmlFor="1">Débutant</label>
                                    <input type="radio" name="difficulte" id="1" value="1" required className="shadow-none" />
                                </div>

                                <div className="flex flex-col items-center gap-2">
                                    <label htmlFor="2">Intermédiaire</label>
                                    <input type="radio" name="difficulte" id="2" value="2" required className="shadow-none" defaultChecked />
                                </div>

                                <div className="flex flex-col items-center gap-2">
                                    <label htmlFor="3">Avancé</label>
                                    <input type="radio" name="difficulte" id="3" value="3" required className="shadow-none" />
                                </div>

                            </fieldset>


                            <div className="w-full flex gap-4 justify-center">
                                <label className="switch">
                                    <input type="checkbox" className="chk" onClick={() => hidden ? setHide(false) : setHide(true)} />
                                    <span className="slider"></span>
                                </label>
                                <div className="flex flex-col h-full justify-between">
                                    <label>Privé</label>
                                    <label>Public</label>
                                </div>
                            </div>

                            <button className="rounded-full bg-[#0E6073] px-10 py-3 font-semibold text-white no-underline transition hover:bg-[#0E6073]/80" type="submit" value="submit">Créer la formation</button>
                        </fieldset>


                    </form>

                </div>

                <Header selected={3} />

                {tab === "tech" &&
                    <div className="fixed w-full h-full bg-[#0E6073]/90 top-0 right-0 left-0 bottom-0 flex justify-center items-center">
                        <form onSubmit={handlerAddTech} className="relative flex flex-col gap-5 justify-center items-center bg-white dark:bg-[#082F38] rounded-xl p-16 w-[30%]" method="POST">
                            <div onClick={() => { setTab("normal"); setLogo("") }} className="absolute top-3 right-4 rounded-full font-semibold  no-underline transition hover:text-red-500 hover:cursor-pointer">
                                <HiXMark className="text-[2rem] text-[#0e6073] hover:text-red-500" />
                            </div>
                            <h1 className="text-xl font-extrabold tracking-tight text-[#0e6073] dark:text-[#1A808C] w-full"><label htmlFor="techName">Nouvelle thématique</label></h1>
                            <input name="techName" id="techName" type="text" placeholder="Nom de la technologie" required className="inputAddForm w-full dark:bg-[#041F25] shadow-[inset_4px_5px_12px_6px_rgba(0,0,0,0.25)]" autoComplete="off"></input>
                            <input name="logoTech" id="logoTech" type="url" placeholder="URL du Logo" required className="inputAddForm w-full dark:bg-[#041F25] shadow-[inset_4px_5px_12px_6px_rgba(0,0,0,0.25)]" autoComplete="off" onChange={(e) => setLogo(e.target.value)}></input>
                            {urlLogo !== "" && urlLogo.length > 8 ? <img src={urlLogo} className="max-w-[6rem] max-h-[6rem] min-x-[0px] min-h-[0px]" /> : <></>}
                            <button className="rounded-full bg-[#0E6073] text-white px-10 py-3 font-semibold w-full no-underline transition hover:bg-[#0E6073]/20" type="submit">Ajouter</button>


                        </form>
                    </div>}

            </main> : <img src="https://media.discordapp.net/attachments/688793736620146689/915869475423813662/20210709_215217.gif" alt="Pas Admnin, Ratio"></img>

            }
        </>
    );
};

export default Admin;

